#!/bin/bash
sudo apt-get install silversearcher-ag
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cd $HOME
wget https://github.com/davidabrahams/dotfiles/raw/master/.vimrc
vim +PlugInstall
