#!/bin/bash

sudo apt-get -y install zsh
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh 
chsh -s `which zsh`
cd $HOME
rm .zshrc && wget https://github.com/davidabrahams/dotfiles/raw/master/.zshrc
git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions

sudo shutdown -r 0
