#!/bin/bash
sudo apt-get -y install vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cd $HOME
sudo apt-get -y install build-essential cmake
sudo apt-get -y install nodejs npm
sudo npm install -g tern
wget https://github.com/davidabrahams/dotfiles/raw/master/.vimrc
vim +PlugInstall
