#!/bin/bash

sudo apt-get update
sudo apt-get -y install build-essential libssl-dev
sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

# sudo npm install -g eslint
# sudo npm install -g eslint_d
# sudo npm install -g babel-eslint
# sudo npm install -g eslint-plugin-react
# sudo npm install -g eslint-config-airbnb-es5

# cd $HOME
# wget https://github.com/davidabrahams/dotfiles/raw/master/.eslintrc
