#!/bin/bash

# Run this using:
# wget https://raw.githubusercontent.com/davidabrahams/dotfiles/master/setup-git && bash setup-git

git config --global user.email "da.j.abrahams@gmail.com"
git config --global user.name "David Abrahams"

git config --global core.editor "vi"
git config --global push.default "current"

git config --global pull.ff only
