#!/bin/bash
sudo apt-get -y install git git-core

git config --global user.email "david.abrahams@students.olin.edu"
git config --global user.name "David Abrahams"


git config --global core.editor "vi"
git config --global push.default "current"
