#!/bin/bash

sudo apt-get -y install zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
rm -f .zshrc
wget https://github.com/davidabrahams/dotfiles/raw/master/.zshrc
sudo git clone git://github.com/zsh-users/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
chsh -s `which zsh`

# sudo shutdown -r 0
