#!/bin/bash

curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | zsh 
cd $HOME
rm .zshrc && curl -O https://github.com/davidabrahams/dotfiles/raw/master/.zshrc
sudo git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions

chsh -s /bin/zsh
