#!/bin/bash

# Run this using:
# wget https://raw.githubusercontent.com/davidabrahams/dotfiles/master/setup-git && ./setup-git
sudo apt-get -y install git git-core

git config --global user.email "da.j.abrahams@gmail.com"
git config --global user.name "David Abrahams"

git config --global core.editor "vi"
git config --global push.default "current"

ssh-keygen -t ed25519 -C "da.j.abrahams@gmail.com"
