#!/bin/bash

# wget https://github.com/davidabrahams/dotfiles/raw/master/setup && bash setup

sudo apt-get install git
sudo apt-get install vim
sudo apt-get install build-essential cmake
sudo apt-get install python-dev python3-dev
sudo apt-get install zsh
sudo apt-get install git-core
sudo apt-get install nodejs
sudo apt-get install npm
sudo apt-get install nodejs-legacy
sudo npm install -g eslint
sudo npm install -g eslint_d
sudo npm install -g babel-eslint
sudo npm install -g eslint-plugin-react
sudo npm install -g eslint-config-airbnb-es5
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh && chsh -s `which zsh`
cd $HOME
mkdir -p Repos && cd Repos
rm -rf dotfiles
git clone git@github.com:davidabrahams/dotfiles.git
bash dotfiles/distribute
vim +PlugInstall
