#!/bin/bash

# wget https://github.com/davidabrahams/dotfiles/raw/master/setup && bash setup

sudo apt-get -y install git
sudo apt-get -y install vim
sudo apt-get -y install build-essential cmake
sudo apt-get -y install python-dev python3-dev
sudo apt-get -y install zsh
sudo apt-get -y install git-core
sudo apt-get -y install nodejs
sudo apt-get -y install npm
sudo apt-get -y install nodejs-legacy

sudo npm install -g eslint
sudo npm install -g eslint_d
sudo npm install -g babel-eslint
sudo npm install -g eslint-plugin-react
sudo npm install -g eslint-config-airbnb-es5

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cd $HOME
wget https://github.com/davidabrahams/dotfiles/raw/master/.vimrc
rm .zshrc && wget https://github.com/davidabrahams/dotfiles/raw/master/.zshrc
vim +PlugInstall

wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh && chsh -s `which zsh`
sudo shutdown -r 0
